[2022-03-21 22:54:50,391] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-21 22:54:50,405] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-21 22:54:50,406] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:54:50,407] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 22:54:50,408] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:54:50,422] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2022-03-21 22:54:50,430] {standard_task_runner.py:52} INFO - Started process 1223 to run task
[2022-03-21 22:54:50,435] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '542', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpas2zjy04', '--error-file', '/tmp/tmpgu0x0wp4']
[2022-03-21 22:54:50,437] {standard_task_runner.py:77} INFO - Job 542: Subtask local_to_gcs_task
[2022-03-21 22:54:50,528] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 22:54:50,576] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 22:54:50,605] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-03-21 22:54:50,622] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 58, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-03-citibike-tripdata.parquet'
[2022-03-21 22:54:50,641] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20220321T225450, end_date=20220321T225450
[2022-03-21 22:54:50,661] {standard_task_runner.py:92} ERROR - Failed to execute job 542 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 58, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-03-citibike-tripdata.parquet'
[2022-03-21 22:54:50,695] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 22:54:50,767] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:05:58,840] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-21 23:05:58,861] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-21 23:05:58,862] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:05:58,863] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:05:58,863] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:05:58,890] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2022-03-21 23:05:58,900] {standard_task_runner.py:52} INFO - Started process 1786 to run task
[2022-03-21 23:05:58,909] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '561', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp19r96tnr', '--error-file', '/tmp/tmp9kgo8gty']
[2022-03-21 23:05:58,912] {standard_task_runner.py:77} INFO - Job 561: Subtask local_to_gcs_task
[2022-03-21 23:05:59,015] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:05:59,083] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:05:59,126] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-03-21 23:05:59,145] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-03-citibike-tripdata.parquet'
[2022-03-21 23:05:59,171] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20220321T230558, end_date=20220321T230559
[2022-03-21 23:05:59,190] {standard_task_runner.py:92} ERROR - Failed to execute job 561 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-03-citibike-tripdata.parquet'
[2022-03-21 23:05:59,246] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 23:05:59,307] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:29:49,012] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-21 23:29:49,035] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-21 23:29:49,037] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:29:49,039] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:29:49,040] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:29:49,060] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2022-03-21 23:29:49,070] {standard_task_runner.py:52} INFO - Started process 3099 to run task
[2022-03-21 23:29:49,078] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '615', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmplqk7qw_5', '--error-file', '/tmp/tmpzju3e38f']
[2022-03-21 23:29:49,081] {standard_task_runner.py:77} INFO - Job 615: Subtask local_to_gcs_task
[2022-03-21 23:29:49,321] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:29:49,421] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:29:49,498] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-03-21 23:30:11,927] {python.py:175} INFO - Done. Returned value was: None
[2022-03-21 23:30:11,941] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20220321T232949, end_date=20220321T233011
[2022-03-21 23:30:11,982] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 23:30:12,018] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 09:05:26,403] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-23 09:05:26,415] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-23 09:05:26,416] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:05:26,417] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 09:05:26,418] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:05:26,429] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2022-03-23 09:05:26,436] {standard_task_runner.py:52} INFO - Started process 1147 to run task
[2022-03-23 09:05:26,441] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '696', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpaw2kksdn', '--error-file', '/tmp/tmplexz6mw1']
[2022-03-23 09:05:26,442] {standard_task_runner.py:77} INFO - Job 696: Subtask local_to_gcs_task
[2022-03-23 09:05:26,509] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 09:05:26,551] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 09:05:26,572] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-03-23 09:05:56,875] {python.py:175} INFO - Done. Returned value was: None
[2022-03-23 09:05:56,889] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20220323T090526, end_date=20220323T090556
[2022-03-23 09:05:56,920] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 09:05:56,953] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:08:23,919] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-23 16:08:23,933] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-23 16:08:23,934] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:08:23,935] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:08:23,936] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:08:23,951] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2022-03-23 16:08:23,960] {standard_task_runner.py:52} INFO - Started process 4285 to run task
[2022-03-23 16:08:23,965] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '1008', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp4r0tdb65', '--error-file', '/tmp/tmp66270b66']
[2022-03-23 16:08:23,966] {standard_task_runner.py:77} INFO - Job 1008: Subtask local_to_gcs_task
[2022-03-23 16:08:24,014] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:08:24,060] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:08:24,086] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-03-23 16:08:52,514] {python.py:175} INFO - Done. Returned value was: None
[2022-03-23 16:08:52,528] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20220323T160823, end_date=20220323T160852
[2022-03-23 16:08:52,572] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:08:52,616] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 10:56:50,358] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-26 10:56:50,375] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-26 10:56:50,379] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:56:50,380] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 10:56:50,381] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:56:50,394] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2022-03-26 10:56:50,403] {standard_task_runner.py:52} INFO - Started process 6436 to run task
[2022-03-26 10:56:50,409] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '1360', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpst74cb9b', '--error-file', '/tmp/tmpx8rua185']
[2022-03-26 10:56:50,414] {standard_task_runner.py:77} INFO - Job 1360: Subtask local_to_gcs_task
[2022-03-26 10:56:50,503] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 10:56:50,567] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 10:56:50,608] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-03-26 10:57:45,379] {python.py:175} INFO - Done. Returned value was: None
[2022-03-26 10:57:45,419] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20220326T105650, end_date=20220326T105745
[2022-03-26 10:57:45,477] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 10:57:45,534] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 15:34:30,837] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-26 15:34:30,859] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [queued]>
[2022-03-26 15:34:30,860] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:34:30,864] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 15:34:30,865] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:34:30,900] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-03-02 06:00:00+00:00
[2022-03-26 15:34:30,918] {standard_task_runner.py:52} INFO - Started process 20389 to run task
[2022-03-26 15:34:30,925] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-03-02T06:00:00+00:00', '--job-id', '1605', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp3g9bhqfy', '--error-file', '/tmp/tmplxvmhrwg']
[2022-03-26 15:34:30,928] {standard_task_runner.py:77} INFO - Job 1605: Subtask local_to_gcs_task
[2022-03-26 15:34:31,022] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-03-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 15:34:31,086] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 15:34:31,128] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-03-02T06:00:00+00:00
[2022-03-26 15:35:36,778] {python.py:175} INFO - Done. Returned value was: None
[2022-03-26 15:35:36,803] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190302T060000, start_date=20220326T153430, end_date=20220326T153536
[2022-03-26 15:35:36,886] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 15:35:36,943] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
