[2022-03-21 22:57:29,927] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-21 22:57:29,952] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-21 22:57:29,954] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:57:29,955] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 22:57:29,958] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:57:29,977] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-02 06:00:00+00:00
[2022-03-21 22:57:29,986] {standard_task_runner.py:52} INFO - Started process 1361 to run task
[2022-03-21 22:57:29,994] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '547', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp5yloayio', '--error-file', '/tmp/tmpas272vdd']
[2022-03-21 22:57:29,996] {standard_task_runner.py:77} INFO - Job 547: Subtask local_to_gcs_task
[2022-03-21 22:57:30,080] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 22:57:30,139] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 22:57:30,178] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-03-21 22:57:30,207] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 58, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-04-citibike-tripdata.parquet'
[2022-03-21 22:57:30,234] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190402T060000, start_date=20220321T225729, end_date=20220321T225730
[2022-03-21 22:57:30,257] {standard_task_runner.py:92} ERROR - Failed to execute job 547 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 58, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-04-citibike-tripdata.parquet'
[2022-03-21 22:57:30,288] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 22:57:30,343] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:09:12,627] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-21 23:09:12,646] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-21 23:09:12,647] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:09:12,648] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:09:12,649] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:09:12,663] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-02 06:00:00+00:00
[2022-03-21 23:09:12,673] {standard_task_runner.py:52} INFO - Started process 1961 to run task
[2022-03-21 23:09:12,679] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '566', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp79zp2mmv', '--error-file', '/tmp/tmprr5in2zg']
[2022-03-21 23:09:12,681] {standard_task_runner.py:77} INFO - Job 566: Subtask local_to_gcs_task
[2022-03-21 23:09:12,754] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:09:12,800] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:09:12,831] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-03-21 23:09:12,855] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-04-citibike-tripdata.parquet'
[2022-03-21 23:09:12,880] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190402T060000, start_date=20220321T230912, end_date=20220321T230912
[2022-03-21 23:09:12,900] {standard_task_runner.py:92} ERROR - Failed to execute job 566 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-04-citibike-tripdata.parquet'
[2022-03-21 23:09:12,933] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 23:09:12,979] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:30:39,546] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-21 23:30:39,562] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-21 23:30:39,563] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:30:39,564] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:30:39,565] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:30:39,581] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-02 06:00:00+00:00
[2022-03-21 23:30:39,589] {standard_task_runner.py:52} INFO - Started process 3158 to run task
[2022-03-21 23:30:39,595] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '619', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp_dkkfcw8', '--error-file', '/tmp/tmpd1vyifmd']
[2022-03-21 23:30:39,597] {standard_task_runner.py:77} INFO - Job 619: Subtask local_to_gcs_task
[2022-03-21 23:30:39,682] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:30:39,743] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:30:39,785] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-03-21 23:31:15,573] {python.py:175} INFO - Done. Returned value was: None
[2022-03-21 23:31:16,073] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190402T060000, start_date=20220321T233039, end_date=20220321T233116
[2022-03-21 23:31:16,665] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 23:31:18,166] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-23 09:08:10,341] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-23 09:08:10,354] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-23 09:08:10,355] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:08:10,356] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 09:08:10,357] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:08:10,369] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-02 06:00:00+00:00
[2022-03-23 09:08:10,378] {standard_task_runner.py:52} INFO - Started process 1328 to run task
[2022-03-23 09:08:10,383] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '705', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmptfkpwaap', '--error-file', '/tmp/tmp38nhp6lq']
[2022-03-23 09:08:10,384] {standard_task_runner.py:77} INFO - Job 705: Subtask local_to_gcs_task
[2022-03-23 09:08:10,452] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 09:08:10,496] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 09:08:10,519] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-03-23 09:08:50,899] {python.py:175} INFO - Done. Returned value was: None
[2022-03-23 09:08:50,913] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190402T060000, start_date=20220323T090810, end_date=20220323T090850
[2022-03-23 09:08:50,967] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 09:08:51,001] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:08:57,751] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-23 16:08:57,764] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-23 16:08:57,765] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:08:57,766] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:08:57,767] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:08:57,778] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-02 06:00:00+00:00
[2022-03-23 16:08:57,785] {standard_task_runner.py:52} INFO - Started process 4325 to run task
[2022-03-23 16:08:57,790] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '1012', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp6hq7kkwy', '--error-file', '/tmp/tmpbfvkjad8']
[2022-03-23 16:08:57,791] {standard_task_runner.py:77} INFO - Job 1012: Subtask local_to_gcs_task
[2022-03-23 16:08:57,864] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:08:57,912] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:08:57,937] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-03-23 16:09:41,939] {python.py:175} INFO - Done. Returned value was: None
[2022-03-23 16:09:41,955] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190402T060000, start_date=20220323T160857, end_date=20220323T160941
[2022-03-23 16:09:42,019] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:09:42,064] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 10:58:33,284] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-26 10:58:33,301] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-26 10:58:33,305] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:58:33,306] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 10:58:33,307] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:58:33,322] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-02 06:00:00+00:00
[2022-03-26 10:58:33,330] {standard_task_runner.py:52} INFO - Started process 6529 to run task
[2022-03-26 10:58:33,338] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '1365', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpycf1htam', '--error-file', '/tmp/tmpa47p792d']
[2022-03-26 10:58:33,341] {standard_task_runner.py:77} INFO - Job 1365: Subtask local_to_gcs_task
[2022-03-26 10:58:33,427] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 10:58:33,482] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 10:58:33,512] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-03-26 10:59:25,512] {python.py:175} INFO - Done. Returned value was: None
[2022-03-26 10:59:25,530] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190402T060000, start_date=20220326T105833, end_date=20220326T105925
[2022-03-26 10:59:25,591] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 10:59:25,643] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 15:35:18,474] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-26 15:35:18,504] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2022-03-26 15:35:18,509] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:35:18,513] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 15:35:18,515] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:35:18,554] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-04-02 06:00:00+00:00
[2022-03-26 15:35:18,577] {standard_task_runner.py:52} INFO - Started process 20434 to run task
[2022-03-26 15:35:18,605] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '1608', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpeng5y4kt', '--error-file', '/tmp/tmpdekvodqd']
[2022-03-26 15:35:18,611] {standard_task_runner.py:77} INFO - Job 1608: Subtask local_to_gcs_task
[2022-03-26 15:35:18,873] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-04-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 15:35:19,060] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 15:35:19,159] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T06:00:00+00:00
[2022-03-26 15:36:32,369] {python.py:175} INFO - Done. Returned value was: None
[2022-03-26 15:36:32,388] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190402T060000, start_date=20220326T153518, end_date=20220326T153632
[2022-03-26 15:36:32,428] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 15:36:32,482] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
