[2022-03-23 15:28:57,780] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [queued]>
[2022-03-23 15:28:57,796] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [queued]>
[2022-03-23 15:28:57,797] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 15:28:57,798] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 15:28:57,799] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 15:28:57,815] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2018-07-02 06:00:00+00:00
[2022-03-23 15:28:57,825] {standard_task_runner.py:52} INFO - Started process 2021 to run task
[2022-03-23 15:28:57,830] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'bigquery_external_table_task', 'scheduled__2018-07-02T06:00:00+00:00', '--job-id', '896', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmprkq1qqq_', '--error-file', '/tmp/tmpct145tvc']
[2022-03-23 15:28:57,832] {standard_task_runner.py:77} INFO - Job 896: Subtask bigquery_external_table_task
[2022-03-23 15:28:57,903] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 15:28:57,948] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 15:28:57,973] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-07-02T06:00:00+00:00
[2022-03-23 15:28:57,975] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-03-23 15:28:59,026] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/healthy-fuze-339218/datasets/citibike_project/tables?prettyPrint=false: Error while reading table: citibike_project, error message: Failed to expand table citibike_project with file pattern gs://dtc_citibike_project/raw//opt/airflow/201807-citibike-tripdata.parquet: matched no files.
[2022-03-23 15:28:59,045] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=bigquery_external_table_task, execution_date=20180702T060000, start_date=20220323T152857, end_date=20220323T152859
[2022-03-23 15:28:59,059] {standard_task_runner.py:92} ERROR - Failed to execute job 896 for task bigquery_external_table_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1196, in execute
    table_resource=self.table_resource,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 408, in create_empty_table
    table=table, exists_ok=exists_ok, retry=retry
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 755, in create_table
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/healthy-fuze-339218/datasets/citibike_project/tables?prettyPrint=false: Error while reading table: citibike_project, error message: Failed to expand table citibike_project with file pattern gs://dtc_citibike_project/raw//opt/airflow/201807-citibike-tripdata.parquet: matched no files.
[2022-03-23 15:28:59,111] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-23 15:28:59,157] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:01:45,211] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [queued]>
[2022-03-23 16:01:45,224] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [queued]>
[2022-03-23 16:01:45,225] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:01:45,226] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:01:45,226] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:01:45,239] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2018-07-02 06:00:00+00:00
[2022-03-23 16:01:45,245] {standard_task_runner.py:52} INFO - Started process 3775 to run task
[2022-03-23 16:01:45,250] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'bigquery_external_table_task', 'scheduled__2018-07-02T06:00:00+00:00', '--job-id', '971', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpa_689qiv', '--error-file', '/tmp/tmppsikep55']
[2022-03-23 16:01:45,251] {standard_task_runner.py:77} INFO - Job 971: Subtask bigquery_external_table_task
[2022-03-23 16:01:45,322] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:01:45,366] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:01:45,386] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-07-02T06:00:00+00:00
[2022-03-23 16:01:45,388] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-03-23 16:01:47,585] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=bigquery_external_table_task, execution_date=20180702T060000, start_date=20220323T160145, end_date=20220323T160147
[2022-03-23 16:01:47,617] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:01:47,660] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 10:38:48,101] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [queued]>
[2022-03-26 10:38:48,130] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [queued]>
[2022-03-26 10:38:48,135] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:38:48,137] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 10:38:48,138] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:38:48,167] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2018-07-02 06:00:00+00:00
[2022-03-26 10:38:48,182] {standard_task_runner.py:52} INFO - Started process 5430 to run task
[2022-03-26 10:38:48,196] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'bigquery_external_table_task', 'scheduled__2018-07-02T06:00:00+00:00', '--job-id', '1320', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpx_a9nmb3', '--error-file', '/tmp/tmp74c3avtn']
[2022-03-26 10:38:48,208] {standard_task_runner.py:77} INFO - Job 1320: Subtask bigquery_external_table_task
[2022-03-26 10:38:48,337] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.bigquery_external_table_task scheduled__2018-07-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 10:38:48,460] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2018-07-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2018-07-02T06:00:00+00:00
[2022-03-26 10:38:48,465] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-03-26 10:38:49,935] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=bigquery_external_table_task, execution_date=20180702T060000, start_date=20220326T103848, end_date=20220326T103849
[2022-03-26 10:38:50,037] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 10:38:50,106] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
