[2022-03-23 09:31:26,857] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-03-23 09:31:26,868] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-03-23 09:31:26,869] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:31:26,870] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 09:31:26,870] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:31:26,884] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-03-02 06:00:00+00:00
[2022-03-23 09:31:26,890] {standard_task_runner.py:52} INFO - Started process 2863 to run task
[2022-03-23 09:31:26,895] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '787', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp4z4180m4', '--error-file', '/tmp/tmpyv8578hh']
[2022-03-23 09:31:26,897] {standard_task_runner.py:77} INFO - Job 787: Subtask download_dataset_task
[2022-03-23 09:31:26,964] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 09:31:27,009] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 09:31:27,040] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-02T06:00:00+00:00
[2022-03-23 09:31:27,043] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 09:31:27,045] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/202103-citibike-tripdata.csv.zip > /opt/***/202103-citibike-tripdata.csv.zip']
[2022-03-23 09:31:27,062] {subprocess.py:85} INFO - Output:
[2022-03-23 09:32:44,257] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-23 09:32:44,305] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20210302T060000, start_date=20220323T093126, end_date=20220323T093244
[2022-03-23 09:32:44,370] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 09:32:44,414] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:48:21,112] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-03-23 16:48:21,125] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-03-23 16:48:21,126] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:48:21,127] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:48:21,128] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:48:21,141] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-03-02 06:00:00+00:00
[2022-03-23 16:48:21,148] {standard_task_runner.py:52} INFO - Started process 6623 to run task
[2022-03-23 16:48:21,153] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '1116', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpt3g7exvw', '--error-file', '/tmp/tmpmkm4vge6']
[2022-03-23 16:48:21,155] {standard_task_runner.py:77} INFO - Job 1116: Subtask download_dataset_task
[2022-03-23 16:48:21,238] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:48:21,288] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:48:21,316] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-02T06:00:00+00:00
[2022-03-23 16:48:21,318] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-23 16:48:21,319] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/202103-citibike-tripdata.csv.zip > /opt/***/202103-citibike-tripdata.csv.zip']
[2022-03-23 16:48:21,336] {subprocess.py:85} INFO - Output:
[2022-03-23 16:50:20,772] {subprocess.py:89} INFO - curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
[2022-03-23 16:50:20,775] {subprocess.py:93} INFO - Command exited with return code 56
[2022-03-23 16:50:20,792] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-23 16:50:20,801] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20210302T060000, start_date=20220323T164821, end_date=20220323T165020
[2022-03-23 16:50:20,823] {standard_task_runner.py:92} ERROR - Failed to execute job 1116 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 56.
[2022-03-23 16:50:20,847] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-23 16:50:20,893] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-26 11:37:18,778] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-03-26 11:37:18,790] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [queued]>
[2022-03-26 11:37:18,791] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:37:18,792] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 11:37:18,793] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:37:18,807] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2021-03-02 06:00:00+00:00
[2022-03-26 11:37:18,814] {standard_task_runner.py:52} INFO - Started process 8826 to run task
[2022-03-26 11:37:18,823] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'download_dataset_task', 'scheduled__2021-03-02T06:00:00+00:00', '--job-id', '1477', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpyxckdynq', '--error-file', '/tmp/tmpbc2hlpwr']
[2022-03-26 11:37:18,824] {standard_task_runner.py:77} INFO - Job 1477: Subtask download_dataset_task
[2022-03-26 11:37:18,913] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.download_dataset_task scheduled__2021-03-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 11:37:18,956] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 11:37:18,980] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2021-03-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-02T06:00:00+00:00
[2022-03-26 11:37:18,983] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 11:37:18,984] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://s3.amazonaws.com/tripdata/202103-citibike-tripdata.csv.zip > /opt/***/202103-citibike-tripdata.csv.zip']
[2022-03-26 11:37:18,998] {subprocess.py:85} INFO - Output:
[2022-03-26 11:38:06,922] {subprocess.py:93} INFO - Command exited with return code 0
[2022-03-26 11:38:07,056] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=download_dataset_task, execution_date=20210302T060000, start_date=20220326T113718, end_date=20220326T113807
[2022-03-26 11:38:07,142] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 11:38:07,241] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
