[2022-03-21 23:18:57,862] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-03-21 23:18:57,874] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-03-21 23:18:57,876] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:18:57,876] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-03-21 23:18:57,877] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:18:57,889] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-06-02 06:00:00+00:00
[2022-03-21 23:18:57,895] {standard_task_runner.py:52} INFO - Started process 2424 to run task
[2022-03-21 23:18:57,900] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '579', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpx2rdz3tc', '--error-file', '/tmp/tmp04ve9t_1']
[2022-03-21 23:18:57,901] {standard_task_runner.py:77} INFO - Job 579: Subtask local_to_gcs_task
[2022-03-21 23:18:57,967] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:18:58,006] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:18:58,028] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-03-21 23:18:58,044] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-06-citibike-tripdata.parquet'
[2022-03-21 23:18:58,061] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190602T060000, start_date=20220321T231857, end_date=20220321T231858
[2022-03-21 23:18:58,074] {standard_task_runner.py:92} ERROR - Failed to execute job 579 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-06-citibike-tripdata.parquet'
[2022-03-21 23:18:58,114] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 23:18:58,160] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:19:38,634] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-03-23 16:19:38,645] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-03-23 16:19:38,646] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:19:38,647] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-03-23 16:19:38,647] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:19:38,659] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-06-02 06:00:00+00:00
[2022-03-23 16:19:38,665] {standard_task_runner.py:52} INFO - Started process 4903 to run task
[2022-03-23 16:19:38,669] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '1028', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp7lk2lxyo', '--error-file', '/tmp/tmpzk2t75d6']
[2022-03-23 16:19:38,671] {standard_task_runner.py:77} INFO - Job 1028: Subtask local_to_gcs_task
[2022-03-23 16:19:38,742] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:19:38,789] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:19:38,815] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-03-23 16:20:23,272] {python.py:175} INFO - Done. Returned value was: None
[2022-03-23 16:20:23,307] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190602T060000, start_date=20220323T161938, end_date=20220323T162023
[2022-03-23 16:20:23,369] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:20:23,416] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 11:09:08,950] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-03-26 11:09:08,967] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2022-03-26 11:09:08,968] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:09:08,969] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-03-26 11:09:08,970] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 11:09:08,991] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-06-02 06:00:00+00:00
[2022-03-26 11:09:09,002] {standard_task_runner.py:52} INFO - Started process 7124 to run task
[2022-03-26 11:09:09,009] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '1390', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpkyi8_con', '--error-file', '/tmp/tmpsc0p77cq']
[2022-03-26 11:09:09,012] {standard_task_runner.py:77} INFO - Job 1390: Subtask local_to_gcs_task
[2022-03-26 11:09:09,110] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-06-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 11:09:09,174] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 11:09:09,208] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-03-26 11:11:37,502] {python.py:175} INFO - Done. Returned value was: None
[2022-03-26 11:11:37,520] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190602T060000, start_date=20220326T110908, end_date=20220326T111137
[2022-03-26 11:11:37,567] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 11:11:37,624] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
