[2022-03-21 22:49:43,895] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 22:49:43,918] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 22:49:43,921] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:49:43,923] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 22:49:43,924] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 22:49:43,958] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 06:00:00+00:00
[2022-03-21 22:49:43,972] {standard_task_runner.py:52} INFO - Started process 976 to run task
[2022-03-21 22:49:43,990] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '535', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpxg1mi149', '--error-file', '/tmp/tmp9ng4f6o6']
[2022-03-21 22:49:43,993] {standard_task_runner.py:77} INFO - Job 535: Subtask local_to_gcs_task
[2022-03-21 22:49:44,126] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 22:49:44,211] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 22:49:44,265] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-21 22:49:44,367] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 58, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-01-citibike-tripdata.parquet'
[2022-03-21 22:49:44,406] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190102T060000, start_date=20220321T224943, end_date=20220321T224944
[2022-03-21 22:49:44,433] {standard_task_runner.py:92} ERROR - Failed to execute job 535 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 58, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-01-citibike-tripdata.parquet'
[2022-03-21 22:49:44,481] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 22:49:44,580] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:00:09,319] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 23:00:09,348] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 23:00:09,349] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:00:09,350] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:00:09,351] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:00:09,370] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 06:00:00+00:00
[2022-03-21 23:00:09,381] {standard_task_runner.py:52} INFO - Started process 1496 to run task
[2022-03-21 23:00:09,386] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpj1zssdwy', '--error-file', '/tmp/tmp1ijfll_g']
[2022-03-21 23:00:09,388] {standard_task_runner.py:77} INFO - Job 552: Subtask local_to_gcs_task
[2022-03-21 23:00:09,479] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:00:09,537] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:00:09,573] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-21 23:00:09,598] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-01-citibike-tripdata.parquet'
[2022-03-21 23:00:09,623] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190102T060000, start_date=20220321T230009, end_date=20220321T230009
[2022-03-21 23:00:09,646] {standard_task_runner.py:92} ERROR - Failed to execute job 552 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/project_data_ingestion.py", line 59, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/2019-01-citibike-tripdata.parquet'
[2022-03-21 23:00:09,682] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 23:00:09,750] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 23:27:54,987] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 23:27:55,003] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-21 23:27:55,007] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:27:55,008] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-21 23:27:55,009] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 23:27:55,025] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 06:00:00+00:00
[2022-03-21 23:27:55,041] {standard_task_runner.py:52} INFO - Started process 2987 to run task
[2022-03-21 23:27:55,043] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '609', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpvdrgnvgm', '--error-file', '/tmp/tmp0ejknfys']
[2022-03-21 23:27:55,045] {standard_task_runner.py:77} INFO - Job 609: Subtask local_to_gcs_task
[2022-03-21 23:27:55,144] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host b91e76d7fa3b
[2022-03-21 23:27:55,212] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-21 23:27:55,241] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-21 23:28:15,768] {python.py:175} INFO - Done. Returned value was: None
[2022-03-21 23:28:15,787] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190102T060000, start_date=20220321T232754, end_date=20220321T232815
[2022-03-21 23:28:15,839] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-21 23:28:15,879] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 09:05:06,498] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 09:05:06,512] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 09:05:06,513] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:05:06,514] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 09:05:06,515] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:05:06,530] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 06:00:00+00:00
[2022-03-23 09:05:06,539] {standard_task_runner.py:52} INFO - Started process 1111 to run task
[2022-03-23 09:05:06,543] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '693', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp9827q7ud', '--error-file', '/tmp/tmpsd3pk3p8']
[2022-03-23 09:05:06,545] {standard_task_runner.py:77} INFO - Job 693: Subtask local_to_gcs_task
[2022-03-23 09:05:06,608] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 09:05:06,652] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 09:05:06,677] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-23 09:05:22,645] {python.py:175} INFO - Done. Returned value was: None
[2022-03-23 09:05:22,659] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190102T060000, start_date=20220323T090506, end_date=20220323T090522
[2022-03-23 09:05:22,722] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 09:05:22,756] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-23 16:06:06,451] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 16:06:06,463] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-23 16:06:06,464] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:06:06,464] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-23 16:06:06,465] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 16:06:06,477] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 06:00:00+00:00
[2022-03-23 16:06:06,484] {standard_task_runner.py:52} INFO - Started process 4109 to run task
[2022-03-23 16:06:06,488] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '995', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpmucu295s', '--error-file', '/tmp/tmp9r3jwot7']
[2022-03-23 16:06:06,489] {standard_task_runner.py:77} INFO - Job 995: Subtask local_to_gcs_task
[2022-03-23 16:06:06,556] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host 7127e26385ba
[2022-03-23 16:06:06,603] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-23 16:06:06,628] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-23 16:06:30,171] {python.py:175} INFO - Done. Returned value was: None
[2022-03-23 16:06:30,213] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190102T060000, start_date=20220323T160606, end_date=20220323T160630
[2022-03-23 16:06:30,287] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-23 16:06:30,383] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 10:53:57,382] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 10:53:57,404] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 10:53:57,405] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:53:57,406] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 10:53:57,407] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 10:53:57,431] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 06:00:00+00:00
[2022-03-26 10:53:57,444] {standard_task_runner.py:52} INFO - Started process 6218 to run task
[2022-03-26 10:53:57,450] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '1344', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmp_dryhkxn', '--error-file', '/tmp/tmp0v1fbu29']
[2022-03-26 10:53:57,452] {standard_task_runner.py:77} INFO - Job 1344: Subtask local_to_gcs_task
[2022-03-26 10:53:57,555] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 10:53:57,640] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 10:53:57,683] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-26 10:54:37,613] {python.py:175} INFO - Done. Returned value was: None
[2022-03-26 10:54:37,627] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190102T060000, start_date=20220326T105357, end_date=20220326T105437
[2022-03-26 10:54:37,672] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 10:54:37,713] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-26 15:33:13,940] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 15:33:13,982] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2022-03-26 15:33:13,985] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:33:13,989] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-26 15:33:13,990] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 15:33:14,043] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 06:00:00+00:00
[2022-03-26 15:33:14,072] {standard_task_runner.py:52} INFO - Started process 20293 to run task
[2022-03-26 15:33:14,091] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dtc_project_ingest', 'local_to_gcs_task', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '1595', '--raw', '--subdir', 'DAGS_FOLDER/project_data_ingestion.py', '--cfg-path', '/tmp/tmpi7exwmpp', '--error-file', '/tmp/tmpfr6xdq_8']
[2022-03-26 15:33:14,100] {standard_task_runner.py:77} INFO - Job 1595: Subtask local_to_gcs_task
[2022-03-26 15:33:14,227] {logging_mixin.py:109} INFO - Running <TaskInstance: dtc_project_ingest.local_to_gcs_task scheduled__2019-01-02T06:00:00+00:00 [running]> on host c800f4dda314
[2022-03-26 15:33:14,297] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-26 15:33:14,345] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dtc_project_ingest
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T06:00:00+00:00
[2022-03-26 15:33:42,530] {python.py:175} INFO - Done. Returned value was: None
[2022-03-26 15:33:42,545] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=dtc_project_ingest, task_id=local_to_gcs_task, execution_date=20190102T060000, start_date=20220326T153313, end_date=20220326T153342
[2022-03-26 15:33:42,575] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-26 15:33:42,616] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
